const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEMS',
  REMOVE_ITEM: 'REMOVE_ITEMS',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
};

export default CartActionTypes;